version: "3.9"

services:
  db:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "./db-data:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
       MYSQL_DATABASE: 'simpleforum_db'
       MYSQL_USER: 'root'
       MYSQL_ROOT_PASSWORD: 'root'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping --password=root"]
      interval: 1s
      timeout: 5s
      retries: 15
  web:
    build: .
    command: bash -c "python manage.py makemigrations
        && python manage.py migrate
        && python manage.py runserver 0.0.0.0:8080
        && alias pman="python manage.py"
      "
    environment:
      - PYTHONPATH=/app/server/
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
